name: DevSecOps CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install bandit

      - name: Run Bandit scan
        run: bandit -r . -f txt -o bandit-report.txt

      - name: Upload Bandit report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-results
          path: bandit-report.txt
